name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag truck_detector
      run: docker tag truck_detector dmitrymenshikov/truck_detector:v1
    - name: Push the tagged Docker image
      run: docker push dmitrymenshikov/truck_detector:v1
