name: Docker Image CI

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag truck_detector
    - name: tag the image
      run: docker tag truck_detector dmitrymenshikov/truck_detector:v1
    - name: Push the tagged Docker image
      run: docker push dmitrymenshikov/truck_detector:v1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag truck_detector
    - name: tag the image
      run: docker tag truck_detector dmitrymenshikov/truck_detector:dev
    - name: Push the tagged Docker image
      run: docker push dmitrymenshikov/truck_detector:dev
